version: '3.8'

services:
  studentapplication:
    image: studentapplication:latest
    build:
      context: .
      dockerfile: StudentApplication/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/StudentApplication.db
    volumes:
      - ./data:/app/data
